stages:
  - build
  - lint
  - test
  - danger

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: gradle:8.4.0-jdk17-jammy

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle
    - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - gradle build -x test

test:
  stage: test
  script:
    - gradle test
    - cat build/jacoco/test/html/index.html | grep -o 'Total[^%]*%'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    when: always
    paths:
      - build/test-results/test/**/TEST-*.xml
      - build/jacoco/test/jacocoTestReport.xml
    expire_in: 30 days
    reports:
        junit: build/test-results/test/**/TEST-*.xml

danger:
  stage: danger
  image: node:18
  only:
    - merge_requests
  script:
    - git clone https://gitlab.com/platinum-open-source/flowops/danger-bot danger-bot
    - cd danger-bot
    - npm install
    - npx danger ci

terraform-lint:
  stage: lint
  script:
    - chmod +x ./ci/scripts/install_tf
    - ./ci/scripts/install_tf
    - chmod +x ./ci/scripts/validate_tf_files
    - ./ci/scripts/validate_tf_files
    - terraform fmt -check=true -recursive

scala-lint:
  stage: lint
  script:
    - chmod +x ./ci/scripts/install_coursier_and_scalafmt
    - ./ci/scripts/install_coursier_and_scalafmt
    - ~/.local/share/coursier/bin/scalafmt --test