stages:
  - build
  - lint
  - test
  - danger

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

image: gradle:8.4.0-jdk17-jammy

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle
    - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  only:
    - master
  stage: build
  script:
    - gradle build -x test

test:
  only:
    - master
  stage: test
  script:
    - gradle test

danger:
  stage: danger
  image: node:18
  only:
    - merge_requests
  script:
    - git clone https://gitlab.com/platinum-open-source/flowops/danger-bot danger-bot
    - cd danger-bot
    - npm install
    - npx danger ci

terraform-lint:
  stage: lint
  image: hashicorp/terraform:latest
  only:
    - master
  script:
    - ./ci/scripts/validate_tf_files
    - terraform fmt -check=true -recursive

scala-lint:
  stage: lint
  only:
    - master
  script:
    - curl -x -o /usr/local/share/coursier https://github.com/coursier/launchers/raw/master/coursier
    - chmod +x /usr/local/share/coursier
    - /usr/local/share/coursier setup
    - /usr/local/share/coursier install scalafmt
    - scalafmt --test