image:
  file: dockerFile
  context: .

tasks:
  - name: Run vault server
    command: |
      echo "Running vault server"
      vault server -dev -dev-root-token-id="root"
      echo "export VAULT_ADDR=http://localhost:8200" >> ~/.bashrc
      echo "export VAULT_TOKEN=root" >> ~/.bashrc
      echo "export TF_VAR_vault_token=root" >> ~/.bashrc
      source ~/.bashrc

  - name: Run Terraform
    command: |
      export TF_VAR_vault_token=root
      export TF_VAR_postgres_username=postgres
      export TF_VAR_postgres_db_password=postgres
      export TF_VAR_postgres_host=localhost
      
      echo "Running Terraform"
      TF_VAR_vault_token=root terraform -chdir=terraform/dev/postgres-provisioner init
      terraform -chdir=terraform/dev/postgres-provisioner apply -auto-approve

      terraform -chdir=terraform/dev/vault-provisioner init
      terraform -chdir=terraform/dev/vault-provisioner apply -auto-approve

      echo "Terraform apply completed"

  - name: Run git setup
    command: |
      echo "Git setup"
      chmod +x ./scripts/setup
      ./scripts/setup