#!/bin/bash
echo "Validating Terraform files..."
tf_dirs=$(find terraform -type d)

for dir in $tf_dirs; do
  if [ -n "$(find $dir -maxdepth 1 -name '*.tf' -print -quit)" ]; then
    tf_dirs_list="$tf_dirs_list $dir"
  fi
done

for dir in $tf_dirs_list; do
  echo "Validating $dir"
  terraform -chdir="$dir" validate
done
echo "All directories validated successfully."