version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

executors:
  gradle-executor:
    docker:
      - image: gradle:8.4.0-jdk17-jammy

  node-executor:
    docker:
      - image: cimg/node:18.20.3

  git-executor:
    docker:
      - image: alpine/git:latest

jobs:
  build:
    executor: gradle-executor
    steps:
      - checkout
      - run:
          name: Set GRADLE_USER_HOME
          command: |
            export GRADLE_USER_HOME=`pwd`/.gradle
      - run:
          name: Gradle Build
          command: gradle build -x test
      - save_cache:
          paths:
            - ~/.gradle
            - build
          key: gradle-cache-{{ .Branch }}-{{ checksum "build.gradle.kts" }}

  test:
    executor: gradle-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
            - gradle-cache-{{ .Branch }}
            - gradle-cache
      - run:
          name: Gradle Test
          command: gradle test

      - run:
          name: Filter Test Results
          command: |
            mkdir -p ./build/test-results-filtered
            find build/test-results/test -name "TEST-*.xml" -exec cp {} ./build/test-results-filtered \;

      - store_test_results:
          path: build/test-results-filtered

      - save_cache:
          paths:
            - ~/.gradle
            - build
          key: gradle-cache-{{ .Branch }}-{{ checksum "build.gradle.kts" }}

  upload-coverage:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ .Branch }}-{{ checksum "build.gradle.kts" }}
            - gradle-cache-{{ .Branch }}
            - gradle-cache
      - codecov/upload:
          file: build/jacoco/test/jacocoTestReport.xml

  danger-bot:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Clone Danger Bot
          command: |
            git clone https://gitlab.com/platinum-open-source/flowops/danger-bot .
      - run:
          name: Install dependencies
          command: |
            npm install -g npx
            npm install
      - run:
          name: Run Danger
          command: npx danger ci

  sync-to-github:
    executor: git-executor
    steps:
      - checkout
      - run:
          name: Push to GitHub
          command: |
            git config --global user.email "${GIT_EMAIL}"
            git config --global user.name "${GIT_NAME}"
            git remote add github https://${USER_BOT_GITHUB_TOKEN}@github.com/${GITHUB_REPO_TO_SYNC}.git
            git push github ${CIRCLE_BRANCH}

  lint-terraform:
    executor: gradle-executor
    steps:
      - checkout
      - run:
          name: Install terraform
          command: |
            chmod +x ./ci/scripts/install_tf
            ./ci/scripts/install_tf
      - run:
          name: Terraform Validate
          command: |
            chmod +x ./ci/scripts/validate_tf_files
            ./ci/scripts/validate_tf_files
      - run:
          name: Terraform Lint
          command: |
            terraform fmt -check=true -recursive

  lint-scala:
    executor: gradle-executor
    steps:
      - checkout
      - run:
          name: Install Coursier and Scalafmt
          command: |
            chmod +x ./ci/scripts/install_coursier_and_scalafmt
            ./ci/scripts/install_coursier_and_scalafmt
      - run:
          name: Scala Lint
          command: |
            ~/.local/share/coursier/bin/scalafmt --test



workflows:
  pipeline:
    jobs:
      - build
      - lint-terraform
      - lint-scala
      - test:
          requires:
            - build
            - lint-scala
      - upload-coverage:
          requires:
            - test
      - sync-to-github:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - dev