#!/bin/bash

echo "🚀 Starting pre hooks..."
echo "----------------------"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCHES="^(master|main)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
  echo -e "\n❌ Cannot push to remote $BRANCH branch. Please create your own branch and use a pull request.\n"
  exit 1
fi

echo -e "✅ Finish checking branch name.\n"
exit 0